name: squarealfa_entity_adapter
description: Annotations to drive the generation of EntityAdapter class and permissions.
homepage: https://www.example.com

version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  squarealfa_entity_annotations: ^1.1.0
  proto_annotations: ^1.1.4
  map_mapper_annotations: ^1.2.0
  defaults_provider_annotations: ^1.1.0

dev_dependencies:
  pedantic: ^1.9.0
