name: squarealfa_entity_adapter
description: Annotations to drive the generation of EntityAdapter class and permissions.
homepage: https://www.example.com

version: 1.0.0

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  squarealfa_entity_annotations: ^1.0.1
  proto_annotations: #^1.0.0
    path: ../../proto_mapper/proto_annotations
  map_mapper_annotations: ^1.0.0
  defaults_provider_annotations: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0
