name: defaults_provider_generator
description: Generates business class Defaults Providers, that provide default values for non-nullable PODO properties

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  source_gen: ^1.0.0
  decimal: ^1.0.0
  defaults_provider_annotations: ^1.0.0
  squarealfa_generators_common: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0

