name: arangodb_repository
description: Concrete implementation of the nosql_repository package for the ArangoDB database.
repository: https://github.com/squarealfa/arango_repository
homepage: https://github.com/squarealfa/arango_repository
version: 1.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  arango_driver: ^1.0.1
  nosql_repository: ^1.0.1
  squarealfa_security: ^1.0.2
  tuple: ^2.0.0


dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.8
