name: security_repository
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  map_mapper_annotations: #^1.0.1
    path: /home/ruicraveiro/sources/dart_framework/map_mapper/map_mapper_annotations
  squarealfa_entity_annotations:
    path: /home/ruicraveiro/sources/dart_framework/entity/entity_annotations


dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  map_mapper_generator: #^1.0.0
    path: /home/ruicraveiro/sources/dart_framework/map_mapper/map_mapper_generator
  squarealfa_entity_generator:
    path: /home/ruicraveiro/sources/dart_framework/entity/entity_generator
  build_runner: ^1.10.2
  build_verify: ^2.0.0
