name: squarealfa_validation
description: Contains annotations to drive validation and classes to represent
  validation results
homepage: https://github.com/squarealfa/dart_framework/tree/main/validation/validation
repository: https://github.com/squarealfa/dart_framework
version: 1.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.9.0
  
dependencies:
  decimal: ^1.0.0
