name: map_mapper_annotations
description: 
  Contains annotations and mappers to allow the mapping between PODOs and Map<String, dynamic> maps 
  used to interact with document databases
version: 1.0.0-dev.0

environment:
  sdk: '>=2.12.0 <3.0.0'


dev_dependencies:
  pedantic: ^1.11.0
