builders:

  entity_adapter_generator:
    import: "package:squarealfa_entity_adapter_generator/squarealfa_entity_adapter_generator.dart"
    builder_factories: ["entityAdapterBuilder"]
    build_extensions: {".dart": ["entity_adapter.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

  # validation_generator:
  #   import: "package:squarealfa_entity_generator/squarealfa_entity_generator.dart"
  #   builder_factories: ["validationGeneratorBuilder"]
  #   build_extensions: {".dart": ["validation.g.part"]}
  #   auto_apply: dependents
  #   build_to: cache
  #   applies_builders: ["source_gen|combining_builder"]
