name: squarealfa_generators_common
description: Common framework for SquareAlfa Dart generators
homepage: 
repository: 
version: 1.0.0


environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  source_gen: ^1.0.0
  
dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.14.4
