name: proto_annotations
description: 
homepage: https://github.com/squarealfa/dart_proto_mapper
repository: https://github.com/squarealfa/dart_proto_mapper
environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  fixnum: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
