name: proto_annotations
description: proto_annotations
homepage: https://github.com/squarealfa/dart_framework/tree/main/proto_mapper/proto_annotations
repository: https://github.com/squarealfa/dart_framework
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  fixnum: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
